apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-stoic-deployment
  labels:
    app: hello_stoic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello_stoic
  template:
    metadata:
      labels:
        app: hello_stoic
    spec:
      volumes:
        - name: hello-stoic-data
          persistentVolumeClaim:
            claimName: hello-stoic-pvc
      containers:
        - name: hello-stoic
          image: ambaxter/hello_stoic:6
          env:
            - name: ST_CONFIG_KEY
              value: config
            - name: ST_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: basic-secret
                  key: mysecret
          volumeMounts:
            - name: hello-stoic-data
              mountPath: /data
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /readiness
              port: 8080
            periodSeconds: 5
